name: solutech_votify
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  cupertino_icons: ^1.0.2
  path_provider: ^2.0.11
  dartz: ^0.10.1
  flutter_localizations:
    sdk: flutter
  iconsax: ^0.0.8
  eva_icons_flutter: ^3.1.0
  riverpod: ^2.3.0
  go_router: ^6.5.3
  dio: ^5.0.1
  oktoast: ^3.3.1
  flutter_feather_icons: ^2.0.0+1
  flutter_screwdriver: ^2.1.0
  flutter_riverpod: ^2.3.1
  internet_connection_checker: ^1.0.0+1
  lottie: ^2.3.1
  mocktail: ^0.3.0
  equatable: ^2.0.5
  intl: any
  fl_country_code_picker: ^0.1.2
  pin_code_fields: ^7.4.0
  flutter_secure_storage: ^8.0.0
  connecteo: ^1.0.2
  core:
    git:
      url: https://github.com/mutuma-designs/solutech_votify.git

  flutter_switch: ^0.3.2
  percent_indicator: ^4.2.3
  flutter_svg: ^2.0.7
  cached_network_svg_image: ^0.0.5
  audioplayers: ^4.1.0
  collection:
  intl_translation: ^0.18.2
  cached_network_image: ^3.2.3
  form_builder_file_picker: ^4.0.0
  form_builder_phone_field: ^2.0.1
  flutter_libphonenumber: ^2.1.4
  flutter_download_manager: ^0.5.5
  url_launcher: ^6.1.12
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.0
  build_runner: ^2.3.3
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.0
  custom_lint:
  riverpod_lint:

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/images/icon.png"
  remove_alpha_ios: true
  

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/